version: "3.9"
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: "rootpassword"
    ports:
      - "5432:5432"

# vim: set expandtab tabstop=2
